language: elixir
elixir:
  - 1.4.1
addons:
  postgresql: '9.4'
  apt:
    packages:
      - wkhtmltopdf
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
